package ThomasMills.MajorProject.BlinkingReminder.data;

import java.awt.image.BufferedImage;

/**
 * UIData class is used as an object containing inforamtation 
 * to displayed on the ConfigStage. The data is gathered in the 
 * run method in the Run class (runner package). Setters and getters
 * auto generated by eclipse. 
 * @author Thomas Andrew Mills	
 *
 */
 public class UIData {
	
	//the image containing the drew reigion of interests
	private BufferedImage displayImage;
	//if the user has a low blink rate
	private boolean lowBlink;
	//if the user has been staring at the screen for too long 
	private boolean longStare;
	//the blink rate per minute of the user
	private int blinksPerMinute;
	//if the face is too small
	private boolean faceTooSmall;
	//how long the user has been looking at the screen for (milliseconds)
	private int gazeDuration;
	//total blinks
	private int totalBlinks;
	
	/**
	 * returns the display image
	 * @return displayImage
	 */
	public BufferedImage getDisplayImage() {
		return displayImage;
	}
	
	/**
	 * sets the displayImage
	 * @param displayImage
	 */
	public void setDisplayImage(BufferedImage displayImage) {
		this.displayImage = displayImage;
	}
	
	/**
	 * returnsLowBlink
	 * @return lowBlink
	 */
	public boolean isLowBlink() {
		return lowBlink;
	}
	
	/**
	 * sets lowBlink
	 * @param lowBlink
	 */
	public void setLowBlink(boolean lowBlink) {
		this.lowBlink = lowBlink;
	}
	
	/**
	 * gets longStare
	 * @return longStare
	 */
	
	public boolean isLongStare() {
		return longStare;
	}
	
	/**
	 * sets longStare
	 * @param longStare
	 */
	public void setLongStare(boolean longStare) {
		this.longStare = longStare;
	}
	/**
	 * gets blinksPerMinute
	 * @return
	 */

	public int getBlinksPerMinute() {
		return blinksPerMinute;
	}
	
	/**
	 * sets blinksPerMinute
	 * @param blinksPerMinute
	 */

	public void setBlinksPerMinute(int blinksPerMinute) {
		this.blinksPerMinute = blinksPerMinute;
	}

	
    /**
     * gets faceTooSmall
     * @return
     */
	public boolean isFaceTooSmall() {
		return faceTooSmall;
	}
	
	/**
	 * sets FaceTooSmall
	 * @param faceTooSmall
	 */

	public void setFaceTooSmall(boolean faceTooSmall) {
		this.faceTooSmall = faceTooSmall;
	}

	
	/**
	 * sets gaze duration
	 * @return
	 */
	public int getGazeDuration() {
		return gazeDuration;
	}

	/** 
	 * gets gaze duration
	 * @param gazeDuration
	 */
	public void setGazeDuration(int gazeDuration) {
		this.gazeDuration = gazeDuration;
	}
	
	/**
	 * gets total blinks
	 * @return
	 */

	public int getTotalBlinks() {
		return totalBlinks;
	}

	/**
	 * sets total blinks
	 * @param totalBlinks
	 */
	public void setTotalBlinks(int totalBlinks) {
		this.totalBlinks = totalBlinks;
	}
	

}
